//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoffieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string KoffieNaam { get; set; }
        public string Landschap { get; set; }
        public Nullable<System.DateTime> Tijd { get; set; }
        public Nullable<int> Sterkte { get; set; }
        public Nullable<int> Suiker { get; set; }
        public Nullable<int> Melk { get; set; }
        public Nullable<int> DeviceID { get; set; }
    }
}
