USE [master]
GO

/****** Object:  Database [InnovativeCoffee]    Script Date: 6/15/2015 11:59:42 ******/
CREATE DATABASE [InnovativeCoffee]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InnovativeCoffee', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\InnovativeCoffee.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'InnovativeCoffee_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\InnovativeCoffee_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [InnovativeCoffee] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InnovativeCoffee].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InnovativeCoffee] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET ARITHABORT OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InnovativeCoffee] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InnovativeCoffee] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InnovativeCoffee] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InnovativeCoffee] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET RECOVERY FULL 
GO

ALTER DATABASE [InnovativeCoffee] SET  MULTI_USER 
GO

ALTER DATABASE [InnovativeCoffee] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InnovativeCoffee] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InnovativeCoffee] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InnovativeCoffee] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [InnovativeCoffee] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InnovativeCoffee] SET  READ_WRITE 
GO

