//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34014
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Stamp : MonoBehaviour {
	public GameObject KneeLeft;
	public GameObject Foot_L;
	private bool StampReady = false;
	private float Distance;
	public GameObject Shake;
	private CamShake camshake;
	public AudioSource FootStamp;

	// Use this for initialization
	void Start () {
		camshake = Shake.GetComponent<CamShake> ();
	}
	
	// Update is called once per frame
	void Update () {
		Distance = KneeLeft.transform.position.y - Foot_L.transform.position.y;
		Distance /= 4;
		//check position of knee vs postion of rightfoot
		if(gameObject.transform.position.y >= (KneeLeft.transform.position.y-Distance)){
			if(!StampReady){
				Debug.Log("AUW deze arrow doet zeer");
			}
			StampReady = true;
		}
		if(gameObject.transform.position.y <= (Foot_L.transform.position.y+Distance) && StampReady){
			if(StampReady){
				Debug.Log("KABOOOOM");
				camshake.shake =1;
				FootStamp.PlayOneShot(FootStamp.clip,0.5f);
			}
			StampReady = false;
		}
	}
	
}
